### ISSUE TITLE
set value when loading

### ISSUE THREAD

**Issue by Alphmega** [foxbenjaminfox/vue-async-computed#12]
`Custom default value, which will be used until the data is loaded for the first time`, but however, how can i set loading value every time with this plugin.
Example, how can i set loading status after i click a btn, and before async data is prepared

**Comment by foxbenjaminfox** [comment]
At the moment there is no integrated way to do that. This plugin has a slightly different goal in mind. What it does is allow you to treat remote data (or otherwise asynchronously accessible data) almost exactly like local synchronous data, without having to have an explicit load step.

This can be very useful, but if you don't want to use it, you can manage without. It's perfectly alright to have an explicit load (such as one triggered by a button click), but you don't need `vue-async-computed` for that.

Here is an example for your use-case:
````javascript
const MyComponent = {
  template: `
  <div>
     <button @click="load">Load data</button>
     <span>{{myData}}</span>
  </div>
`,
  data () {
    return {
      myData: 'Press the button to load the data.'
    }
  },
  methods: {
    load () {
      this.myData = 'Loading data from server.'
      this.$http.get('/some/url').then(response => {
        this.myData = response.data
      })
    }
  }
}
````

As you can see, there is no need for computed properties at all, just a method to be called whenever the button is clicked.

So when should you use `vue-async-computed`? When it's not a button click (or another specific event) that loads the data, but rather you want some data that is derived from some other properties (whether component props, vuex state, component data, or other computed properties.) Normally, you'd use a computed property for that, but if the calculation to derive the data needs to be asynchronous (such as if it involves AJAX, or WebWorkers, or IndexedDB, or any of the other browser APIs which are async-only), then you can't use a normal computed property, but you can use an asyncComputed property if you use this plugin.

It's a rather different use case, and you may find you need async computed properties eventually. But for a simple "load the data when the button is clicked", you don't need this plugin, and you can do it simply and easily in the manner I gave an example of above.

**Comment by Alphmega** [comment]
I am sorry not described this issus clearly, actually, the btn trigger some other properties change that will cause async properties change
```
const MyComponent = {
  template: `
  <div>
     <button @click="load('something')">Load Something</button>
     <button @click="load('something else')">Load Something else</button>
     <span>{{myData}}</span>
  </div>`,
  data () {
    return {
      loadWhat: 'something'
    }
  },
  asyncComputed: {
    async myData(){
      return (await this.$http.get('/some/url', { loadWhat: this.loadWhat })).data
      });
    }
  },
  methods: {
    btnClick (loadWhat) {
      this.loadWhat = loadWhat;
    }
  }
}
```

**Comment by foxbenjaminfox** [comment]
I see what you mean, and I see why you want to use `vue-async-computed` for that. Indeed, perhaps this is a reasonable use case for `vue-async-computed`.

Nevertheless, I feel that the example is slightly stretching what `vue-async-computed` is meant to do: My goal with `vue-async-computed` is to make the fact that the computed data is asynchronous completely transparent, so that you can treat it almost exactly the same way you'd treat regular computed properties.

But as I said, I do see your use case, and while it is slightly outside the scope of `vue-async-computed` as I originally envisioned it, I agree it's a reasonable extension.

There is an easy, but undocumented, way to get `vue-async-computed`  to do this. Hopefully in the future I'll clean it up and document it properly, if it's something that people need.

You can overwrite an async computed property synchronously within the asyncComputed function, and the computed value will automatically reset to the correct computed value once the promise resolves.

In other words, you can do this:

````javascript
const MyComponent = {
  template: `
  <div>
     <button @click="btnClick('something')">Load Something</button>
     <button @click="btnClick2('else')">Load Something else</button>
     <span>{{myData}}</span>
  </div>`,
  data () {
    return {
      loadWhat: 'something',
      loadWhat2: 'else'
    }
  },
  asyncComputed: {
    async myData(){
      this.myData = 'Loading myData'
      return (await this.$http.get('/some/url', { loadWhat: this.loadWhat + this.loadWhat2 })).data
    },
    async myData2(){
      this.myData2 = 'Loading myData2'
      return (await this.$http.get('/some/url2', { loadWhat: this.loadWhat + this.loadWhat2 })).data
    }
  },
  methods: {
    btnClick (loadWhat) {
      this.loadWhat = loadWhat;
    },
    btnClick2 (loadWhat) {
      this.loadWhat2 = loadWhat;
    }
  }
}
````

This will cause the effect you want: Whenever one of the dependencies change, the value of `myData` and `myData2` immediately (actually, on the [next tick](https://vuejs.org/v2/api/#Vue-nextTick)) take on a value which is a loading message, while at the same time issuing the async request. Then when the async request resolves, the properties go back to having the appropriate computed value.

**Comment by Alphmega** [comment]
Actually, i did the same as what you said before your reply,
But i hope you will considering this feature in the future. :stuck_out_tongue_closed_eyes:

**Comment by foxbenjaminfox** [comment]
I'm glad you've found your solution.

I will keep this in consideration as a formal feature to add in the future. :smiley:
