### ISSUE TITLE
Firefox report error when using `get` function with latest version

### ISSUE THREAD

**Issue by Alphmega** [foxbenjaminfox/vue-async-computed#19]
See demo
https://jsfiddle.net/nx497qxq/3/
version: Vue 2.3.3 Async-computed 3.1.2

**Comment by foxbenjaminfox** [comment]
Yup, that's a pretty nasty bug. It escaped being caught by the automated test suite because the tests get run with the Webkit engine, and the bug only shows up in Gecko. I'll need to consider how to arrange for the tests to run under multiple browser engines, to prevent anything like this from happening again.

In any case, I have released `vue-async-computed@3.1.3` which fixes this bug.
