### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by rasantiago** [foxbenjaminfox/vue-async-computed#2]
This plugin has been a life saver for me and my team.  Thank You!

One issue we run into, though, is that we get Vue warnings from our templates when the asyncComputed property has not yet resolved.  Do you think there is any way to set a default value that is returned while the promise(s) has not resolved?

**Comment by foxbenjaminfox** [comment]
Awesome, I'm glad you like it!

It's true that the real tough part of async properties as opposed to sync ones is how to handle them until the promise resolves. The way I implemented it is that the property is `null` until then, which is fine, but I agree far from ideal.

It means that either you do null checks every place that you use the async property, or that you suffer the warnings. Neither is terrible, but neither is nice and clean.

Sadly, I'm not sure how to best avoid this. The idea I've been thinking of the most is to allow you to set a different default (instead of `null`) for any async properties that `null` would be a problem in.

It would go something like this:

```javascript
new Vue({
  asyncComputed: {
    x () { ... },
    y () { ... },
    z () { ... }
  },
  asyncComputedDefaults: {
    x: "some default for x",
    y: "some default for y"
    // and if we leave out a property, it defaults back to null.
  }
})
````

I'm open to suggestions on a better name than `asyncComputedDefaults`, or for improvements to this API.

Once Vue 2.0 is properly released, I intend to convert this plugin to work properly with Vue 2.0. So I will be doing some major work on this plugin fairly soon, and this is one of the features I was considering adding at the same time. As it seems that this is indeed something people find important, I've pushed it to the top of the list of features I've been considering adding.

**Comment by jin5354** [comment]
Looking forward to the asyncComputedDefaults feature.
Now I'm doing null checks everywhere...

**Comment by foxbenjaminfox** [comment]
I actually went with a slightly different syntax to define default values, inspired by the way the core Vue library [allows you to define more complicated computed properties](https://vuejs.org/guide/computed.html#Computed-Setter).

So the new syntax works like this:
````js
new Vue({
  asyncComputed: {
    x: {
      get () { ... },
      default: "some default for x"
    }
  }
}
````
This allows you to keep all the configuration for a given property all in the same place, as opposed to defining the getter function in one place and the default in another.

I hope you find this feature useful.
