### ISSUE TITLE
Possibility of passing a property (acting as a method)

### ISSUE THREAD

**Issue by veksen** [foxbenjaminfox/vue-async-computed#4]
Would it be possible to pass an argument? I can "hack" it on a computed property like below, but asyncComputed properties expect a return that is a promise.

```
asyncComputed: {
  totals() {
    return {
      inDay(date) {
        return date;
      }
    }
  }
}
```

**Comment by foxbenjaminfox** [comment]
Well, it expects a promise as the return value for a reason: if you aren't returning a promise, you can just use regular computed properties.

Perhaps I'm just not understanding your use case. Can you give an example of what you want to be able to do?

**Comment by veksen** [comment]
Sorry, I wasn't really clear. I'm currently using a method instead a computed property, but I'd like that to be async.

Computed properties do not take arguments, but it can still be possible with the example I showed up top. Would it be possible to pass an argument to an asyncComputed, either directely or indirectly?

`{{ totals(date) }}` or `{{ totals.inDay(date) }}`

**Comment by wmhilton** [comment]
Um, I think this was just a total misunderstanding. Vue already has methods... and computed properties are a separate concern from methods. I think you can safely close this.

**Comment by foxbenjaminfox** [comment]
@wmhilton: You're not wrong. It is indeed a totally separate concern. But it would be nice to be able to have asynchronous methods that return promises, and use them transparently in a template.

Effectively, what @veksen is asking for is a way to use `await` inside an interpolation in a template. That would be nice: To perhaps be able to write `{{ await myMethod() }}` and have it just work.

It is true that it kind of is beyond the scope of this plugin, which deals with computed properties, not with methods. But on the other hand, it is somewhat related. And that's why I've left this open so far, because if I can think of a simple and easy way to implement this functionality I'll do it, although perhaps in a separate plugin.

Unfortunately, at the moment that doesn't seem so likely, as it seems like it would need major structural changes to the way templates are rendered. So unless I find some cool way to work around that, I might just close this issue soon anyway.

**Comment by wmhilton** [comment]
>But it would be nice to be able to have asynchronous methods that return promises... to perhaps be able to write `{{ await myMethod() }}` and have it just work.

Whoa! OK, I kinda see what you're getting at. I can't see the use case (yet) but that's probably just me: I don't think I've ever used a method call in a template except as an event handler. I would consider the method call part of the "logic" and have that done in the `<script>` of a component rather than in the `<template>`.

Yes, I don't think you'll be able to solve "the async problem" entirely, in one vue plugin. Although you never know, this might be the use scenario that finally resolves everything into crystal clarity.

**Comment by foxbenjaminfox** [comment]
You're entirely correct in that methods are generally more logic-like. But a very important use for methods is as pseodo-computed properties that take arguments. Yes, you could also use filters for that purpose, but sometimes a method is easier. For instance, [this part](https://vuejs.org/guide/list.html#Displaying-Filtered-Sorted-Results) of the guide has a bit about using a method to replace a computed property.

But while usually  you can do that, and swap out a computed property for a method if you need to parameterize it, you can't do that for a aysnc computed property. That's where this whole story started, and that's how this issue is related to this plugin.

I agree that most likely this won't be the use scenario that finally resolves everything into crystal clarity, but I do agree with @veksen that it would be kind of nice to have. The only question is whether or not it's possible to do without rewriting the whole Vue templating system, which would be way too much effort for this (relatively minor, all things considered) feature.

**Comment by foxbenjaminfox** [comment]
For the reasons discussed above, I think it unlikely that this will be implemented any time soon, so I'm closing this issue.

I'll keep my eyes open though. Who knows, perhaps I'll find a nice and elegant way to implement this at some point.
