### ISSUE TITLE
On Promise error from async computed method, call default()?

### ISSUE THREAD

**Issue by omarsotillo** [foxbenjaminfox/vue-async-computed#46]
Hello! :+1: 

I think the current behaviour is just render default on start and only reacts with on resolve from the promise but never from the reject of the Promise. 

Example given this code: 

```
asyncComputed: {
    menuDynamic: {
      lazy: true,
      get() {
        return () => {
          return import(`./menus/${this.$user.role}.js`).catch(() => {
            return import('./menus/default.js');
          });
        };
      }
    }
  },
```

I would love using default instead of catch and return default when the first import is failed.

Kind regards,
omar

**Comment by omarsotillo** [comment]
If you need any help with this let me know :smile:

**Comment by foxbenjaminfox** [comment]
I think that silently using the default value as a fallback is a bad idea, on the principle that silently ignoring errors is bad. Specifically, if a component has a bug in it that causes an error to be thrown, you probably want to display either an error page, or the last known good data. You usually wouldn't want to show the default result, which could be a loading message or the like.

It seems that in your scenario you do want to show that same default, but we don't want to force that choice on all users of `vue-async-computed` who don't opt into this. It's not a good default behavior for everyone who sets a `default`, even if it is useful in your case.

So I propose instead a different property on the asyncComputed definition, say `fallback`, that can go next to `default`, which holds a value (or a function that returns a value) that serves as the fallback value for the case of errors. This allows those who want a fallback to have a fallback, without imposing this behavior on everyone who uses `default`.

So you might use it like this:
```
asyncComputed: {
    menuDynamic: {
      lazy: true,
      fallback: import('./menus/default.js');
      get() {
        return () => {
          return import(`./menus/${this.$user.role}.js`);
        };
      }
    }
  }
```

In addition, perhaps we could have a config option for the plugin, `useDefaultAsFallback`, which would use the `default` value also as the `fallback` value if there isn't a separate `fallback` value provided. Then you would only need to set this option in order to have the exact behavior you're asking for:

```
Vue.use(VueAsyncComputed, {
  useDefaultAsFallback: true
})
```

What do you think about all this?

**Comment by michaelzangl** [comment]
Error handling and default value should be two different things.

The default value is usually a null value that can be used in place of the real (success) value that comes from the server (e.g. an empty list). It makes writing vue templates much easier.

What you are trying to do is very specific and this is exactly what the promise try / catch is meant for. That way, you are free to write your error handling any way you want. You can even add two fallbacks, like:
```
      get() {
        return () => import(`./menus/${this.$user.role}.js`)
                  .catch(() => import('./menus/default.js')));
        };
      }
```

Implementing an "easier" mechanism that would save you ~1 line of source code would not make your code easier to read and would not be useful in a general case. Especially since the fallback can be asynchronous as well and can cause errors while loading.

**Comment by foxbenjaminfox** [comment]
@michaelzangl: Agreed. All things considered, I wouldn't really mind adding a config option along the lines of the `useDefaultAsFallback` I proposed, but you're right that this really isn't that useful or idiomatic.

I think I'm going to close this issue now. @omarsotillo, if you still feel strongly about this, perhaps let me know what you think about the proposed `useDefaultAsFallback` option, and we can continue the discussion from there.

**Comment by michaelzangl** [comment]
@foxbenjaminfox  About the setting: This would make using vue-async-computed in libraries impossible since libraries can't expect any specific behavior. Global options are always a pain for compatibility / modularity.
