### ISSUE TITLE
upload as script tag

### ISSUE THREAD

**Issue by fega** [foxbenjaminfox/vue-async-computed#6]
Hello, I'm new in Vue js and module loading...

i want to to upload the plugin using something like

	<script src="./vue.async.js"></script>

How can I achieve that?

thanks

**Comment by foxbenjaminfox** [comment]
In general, I'd recommend using npm to fetch your dependencies, reguardless of wether you are using a module system like webpack or including the scripts directly in your page.

But if you're new to all this that might be a bit more than you want to take on right now. If you want to just link to it on a CDN you can:

````html
<script src="https://unpkg.com/vue-async-computed@2.1.1"></script>
````

I just now added an explanation to the README about this. Be sure to include that script tag after Vue's script tag, so that `vue-async-computed` can register itself on the global Vue instance.

If you don't want to use a CDN, I suppose you could save [that file the CDN serves](https://unpkg.com/vue-async-computed@2.1.1) locally, call the file `vue.async.js`, and use the exact script tag you proposed.

But if you are willing to learn how to use npm, the simplest way is to just run `npm install vue-async-computed` in the appropriate directory. What that does is that it creates a `node_modules` folder, and within it a `vue-async-computed` folder with this module.

In that case the script tag you would use would be something like

````html
<script src="./node_modules/vue-async-computed/dist/index.js"></script>
````

Any of these options are reasonable, although using npm is the most flexible, as (among other things) it allows you to update to a newer module very easily. (With `npm update`.) Whereas if you download the script manually updating to a newer version is a bit harder.

For simplicity's sake, I'd recommend linking it from the CDN. Then you neither need to deal with npm just yet, nor do you have to download things manually. All you need to do is include the script tag and it will work. Updating versions is as simple as changing the version number in the link.

But you choose what you feel is best for you and for your project. These all are available options for using this (or any other) module directly from a script tag.

**Comment by fega** [comment]
Hello  fox, thanks for the explanation, I already know how to use npm, and I'm comfortable with. 
I'm new with browserify and webpack and it seems to be so complicated for the little projects that I'm working on. also, I'm new with this MVC and MVVM frameworks like Vue or react, so I tend to put everything as:
`<script src="https://unpkg.com/vue-async-computed@2.1.1"></script>`

Like in the old school 😆 , also, I seem this tools as too complicated for quick experiments. I was using yesterday the vue-cli, and it's awesome, but sometimes I only want a single HTML file.

Thanks for allowing CDN support!

**Comment by foxbenjaminfox** [comment]
Sure, glad you find it useful. :smiley:
