### ISSUE TITLE
possibility to access the actual Promise

### ISSUE THREAD

**Issue by Buntelrus** [foxbenjaminfox/vue-async-computed#76]
I came in touch with this plugin while researching on the following problem:
So far I loaded data asynchronously using vue methods into vue data properties. I adapt the example given in the README for better understanding.

```js
new Vue({
  data: {
    user: null
  },
  methods: {
    fetchUser (userId) {
      Vue.http.get('/get-username-by-id/' + userId)
        .then(response => {
          this.user = response.data.username
        })
    }
  },
  created() {
    if (this.$router.params.userId) {
      this.fetchUser(this.$router.params.userId)
    }
  }
})
```
this works great until I want to do something with the data before they are available. For example redirecting to the users latest post. I can't do this:

```js
new Vue({
  data: {
    user: null
  },
  methods: {
    fetchUser (userId) {
      Vue.http.get('/get-username-by-id/' + userId)
        .then(response => {
          this.user = response.data
        })
    }
  },
  created() {
    if (this.$router.params.userId) {
      this.fetchUser(this.$router.params.userId)
    }
    if (this.$router.params.action === 'showLatestPost') {
      // this fails because user is null
      this.$router.push(this.user.posts.pop().url)
    }
  }
})
```

This plugin helps to handle asynchronous data but the problem will be the same.

```js
new Vue({
  data: {
    userId: 1
  },
  asyncComputed: {
    user () {
      return Vue.http.get('/get-username-by-id/' + this.userId)
        .then(response => response.data)
    }
  }
  created() {
    if (this.$router.params.action === 'showLatestPost') {
      // this still fails because user is still null
      this.$router.push(this.user.posts.pop().url)
    }
  }
})
```
In this case it would be nice to access the pending promise. I imagine something like this:
```js
new Vue({
  data: {
    userId: 1
  },
  asyncComputed: {
    user () {
      return Vue.http.get('/get-username-by-id/' + this.userId)
        .then(response => response.data)
    }
  }
  created() {
    if (this.$router.params.action === 'showLatestPost') {
      // what I want to do
      this.user.then(user => {
        this.$router.push(user.posts.pop().url)
      })
      // or
      this.$asyncComputed.user.promise.then(user => {
        this.$router.push(user.posts.pop().url)
      })
    }
  }
})
```

**Comment by Buntelrus** [comment]
I figured out that you can access the promise with `this._async_computed$user`. But is this best practice?

**Comment by foxbenjaminfox** [comment]
The best practise would be to use Vue's `watch`, something like this:

```javascript
new Vue({
  data: {
    userId: 1
  },
  asyncComputed: {
    user () {
      return Vue.http.get('/get-username-by-id/' + this.userId)
        .then(response => response.data)
    }
  }
  watch: {
    user () {
      if (this.$router.params.action === 'showLatestPost') {
          this.$router.push(user.posts.pop().url)
      }
    }
  }
})
```
Not only is this simpler and more idiomatic, it will also handle for you the case when `this.userId` changes (and so `this.user` is recalculated) by applying the logic of possibly redirecting to the user's latest post then too. (Of course, if you for some reason _don't_ want this to happen, this logic should only apply to the original user loaded, you can keep track of that original `userId` and check (in the `user`-watching function) that the current `userId` matches the original one.)

I strongly recommend that you don't directly access `this._async_computed$user`, which is an internal implementation detail. (In general in Vue, properties beginning with an underscore should be considered private and internal, and you shouldn't mess with them unless you really know what you're doing.)

What `vue-async-computed` is best at is making what otherwise would need to be handled in it's own special way (asynchronously) instead into something that is able to be handled by Vue's straightforward existing mechanisms, in this case `watch`. You don't need to do anything `Promise`-related at all, other than returning a `Promise` from your function.

**Comment by Buntelrus** [comment]
Many thanks for your answer. This helped me a lot.
I don't need the promise if I instead watch the async computed property. If it is not `null` i can do whatever I would do in `Promise.then()`

**Comment by Buntelrus** [comment]
Maybe I was wrong in my comment before. In my case I have async computed property `serie` which will either fetch needed data or load it from Indexed DB. If I want to something when `serie` becomes available I could do it with `Promise.then()` or watch `serie`. This is all great but I want to do something when a certain query parameter is given. 

```js
if (this.$route.query.hasOwnProperty('play')) {
    this.serie.play()
}
```

Therefore I have to watch `this.$route`. If the parameter is present I have to wait for `serie` which may be always there or not. Therefore I thought it would be nice to access the Promise. If I do my action within a watch for `serie` this maybe misses query parameter changing. If I do my action within watch for `this.$route` it maybe fails because `serie` is not available yet.

**Comment by foxbenjaminfox** [comment]
This is easier than you might think. It doesn't seem that Vue supports this directly with its `watch` API, but its [`$watch`](https://vuejs.org/v2/api/#vm-watch) API method does.

You can call it like this:

```javascript

this.$watch(function() {
  // compute here something that depends on both `this.$route.query` and `this.serie`.
}, function(newVal, oldVal) {
  // Every time the value computed by the first callback changes, this second callback is called.
  // This will happen every time `this.$route.query` or `this.serie` changes.
})
```
